on:
  push:
    branches:
      - 'master'
env:
  NS: uat-qoala
  EKS_CLUSTER_NAME: qoala-dev-cluster
  ENV: uat
  ROLE: arn:aws:iam::744994327583:role/eks-qoala-dev-cluster-ci-role
  
jobs:
  helm-deployment:
    runs-on: [self-hosted, eks-runner]

    outputs:
      image_registry: ${{ steps.publish_image.outputs.image_registry }}
      image_meta: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Declare Github commit hash
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: qoala-engineering/setup-eks-helm-action
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/actions/setup-eks-helm-action

      - uses: ./.github/actions/setup-eks-helm-action
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ env.ROLE }}
          github-token: ${{ secrets.GIT_HUB_TOKEN }}
          cluster-name: ${{ env.EKS_CLUSTER_NAME }}

      - name: Checkout SSM Injection
        uses: actions/checkout@v2
        with:
          repository: qoala-engineering/helm-values-ssm-injection
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/actions/helm-values-ssm-injection

      - name: SSM Injection
        id: values
        uses: ./.github/actions/helm-values-ssm-injection
        with:
          image: almasaabi/nginx:latest
          environment: ${{ env.ENV }}
          configPath: iac/service.config.yaml
          
      - name: Values file content
        id: vars
        shell: bash
        run: |
          cat ${{ steps.values.outputs.values }} && ls charts
      
        